import Foundation

public enum ImageName: String {
    case soundImage = "soundImage"
    case smallButtonBackImage = "smallButtonBackImage"
    case buttonBackImage = "buttonBackImage"
    case musicImage = "musicImage"
    case womanImage = "womanImage"
    case menuBackImage = "menuBackImage"
    case smallButtonForLevelsImage = "smallButtonForLevelsImage"
    case levelBackgroundImage = "levelBackgroundImage"
    case backArrowImage = "backArrowImage"
    case blueBlock = "blueBlock"
    case currenTimeBackgroundImage = "currenTimeBackgroundImage"
    case doubleScoreBackgroundGameImage = "doubleScoreBackgroundGameImage"
    case greenBlock = "greenBlock"
    case helpImage = "helpImage"
    case lineWithArrowImage = "lineWithArrowImage"
    case orangeBlock = "orangeBlock"
    case pinkBlock = "pinkBlock"
    case purpleBlock = "purpleBlock"
    case scoreImage = "scoreImage"
    case timeBackgroundGameImage = "timeBackgroundGameImage"
    case timeImage = "timeImage"
    case yellowBlock = "yellowBlock"
    case gameBackgroundImage = "gameBackgroundImage"
    case shopBackground = "shopBackground"
    case coinCount = "coinCount"
    case shopItemBackground = "shopItemBackground"
    case timeBuy = "timeBuy"
    case doubleBonus = "doubleBonus"
    case fortune = "fortune"
    case rulesBack = "rulesBack"
    case levelBackgroundImage2 = "levelBackgroundImage4"
    case levelBackgroundImage3 = "levelBackgroundImage3"
    case levelBackgroundImage4 = "levelBackgroundImage2"
    case lockedLevel = "lockedLevel"
    case borderFortune = "borderFortune"
    case pick = "pick"
    case numbers = "numbers"
}
